#####################################################################
# BOTTOM LINE VERSION 1.2 FOR SPIGOT                                #
# BY BANJO226 / ILLUMINATIBREAD                                     #
# IF ERRORS ARE PRESENT PLEASE CHECK ERRORS FOR MISTAKES            #
# Common mistakes include:                                          #
# - Tabs (long spaces used by the tab button)                       #
#   YAML does not support these.                                    #
# - Not using quotes around colour coded configuration sections     #
#   YAML only accepts special characters in quotes                  #
# If you have issues trying to find errors, copy and paste this     #
# configuration file into a YAML Parser                             #
#####################################################################
# DO NOT CHANGE THIS LINE OF CONFIGURATION!                         #
# Changing this line will reset config and save this to a new file! #
# This is the configuration updater.                                #
#####################################################################
version: 1.2

# METRICS #
# This plugin utilises Hidendra's plugin metrics system. Opting out of this service can be done by changing this option
# to false or changing opt-out to true in the file plugins/Plugin Metrics/config.yml. The following information is collected and sent to mcstats.org.
#      A unique identifier
#      The server's version of Java
#      Whether the server is in offline or online mode
#      The plugin's version
#      The server's version
#      The OS version/name and architecture
#      The core count for the CPU
#      The number of players online
#      The Metrics version
metrics: true

noPermissionMessage: '&cYou do not have permission to execute this command!'

# ECONOMY #
# Setting the default amount of money, money symbol etc.
# default-amount is the amount of money a player starts with.
economy:
  default-amount: 1000.00
  bal-top: 10000000000.00
  negative-bal: false
  money-symbol: '$'

# BROADCAST #
# This includes the format, whether there is a timeout or not. 
# If timeout is false, the timeoutInSeconds wont be used.      
# Ops and players with bottomline.admin will bypass timeouts.  
broadcast:
  format: '&8[&bBroadcast&8] &c%message%'
  timeout: false
  timeoutInSeconds: 5
  actionbar-broadcast: true

# LAW #
# This changes the messages for the law parts.
# This also has the commands to block for muting and jailing
# For every command, add ** to one of the lists.
# The block list is words or phrases to block.
# %word% is the bad word said in the swear filter.
# Smart checking is where the plugin checks for phrases like 'hshiti' with a swear word in it, if not it will just find the words.
# OfflineBan is if players can ban offline players or not
# For the CPS checker, if you dont want to take health just set the option to 0
law:
  crimeMessage: '&4You do the crime, you do the time.'
  freeze:
    noMove: '&4You are frozen, you cannot move at the moment.'
  mute:
    noSpeak: '&4You are muted, you cannot speak!'
    commands:
    - msg
    - m
    - r
    - reply
    - bukkit:msg
    - bukkit:tell
    - tell
    - message
    - report
  jail:
    noSpeak: '&4You are jailed, you cannot speak!'
    commands:
    - msg
    - m
    - r
    - reply
    - bukkit:msg
    - bukkit:tell
    - tell
    - message
    - tpa
    - tpahere
    - tp
    - spawn
    - s
    - helpop
    - report
    - suicide
    - kill
  kick:
    message: '&c» &4You have been kicked by &l%sender% &4because &l%message%'
    noMessageProvided: 'Misconduct'
  block:
    enabled: true
    smartChecking: true
    blocked: '&4You cannot swear on this server! Word: &c%word%'
    list:
    - fuck
    - fucktard
    - shitstir
    - shit
    - cunt
    - nigga
    - nigs
    - nigger
    - niga
    - niger
    - niggs
    - whore
    - cock
    - pussy
    - vagina
    - jizzle
    - cum
    - jiz
    - jizz
  ban:
    offlineBan: true
    kickMessage: '&c» &4The ban hammer has spoken (by %sender%&c): &c%message%'
    tempBanKick: '&c» &4The ban hammer has spoken (by %sender%&c): &c%message%&4. Your ban expires in %time%'
    tryToJoinKick:
    - '&c» &4You have been banned from this server by &c%sender%'
    - '&cReason: &o%message%'
    - '&cYou may submit an appeal on the forums!'
    tempBanJoinKick:
    - '&c» &4You have been banned from this server by &c%sender%&c!'
    - '&cExpires in: &o%time%'
    - '&cReason: &o%message%'
    - '&cYou may submit an appeal on the forums!'
  cps:
    max-clicks: 20
    kickPlayer: true
    kickMessage: '&4» &cYou have gone over the CPS limit! The limit is %max% and you did %clicks%'
    takeHealth: 5
    commands:
    - 'broadcast &4%player% &cwent over the clicks per second limit by %byclicks% clicks!'
  
# ADMINCHAT #
# This is a chat feature that lets admins speak in private.          
# Format tags are %player% for displayname and %message% for message 
# If toggle is true you can do /a toggle to toggle messages          
adminchat:
  format: '&8[&cAdminChat&8] &4%player% &8> &f%message%'
  toggle: true
  
# RULES #
# Add another line with a - infront of it to add another line, and put the rule in the quotes. 
# If you want to use an apostrophe use double quotes around the rule instead of a single quote 
# to prevent errors, same goes with double but the other way around. Example:                  
# - "&4[1] &bI'm a rule with an apostrophe in it!"                                             
# - '&4[2] &bI am a rule with "double" quotes in it!'                                          
rules:
- '&c[A] &4Be nice'
- '&c[B] &4Use manners'
- '&c[C] &4Have fun'

# MOTD #
# The same rules apply with the rules part of the configuration. 
# Tags include the following:
# - %player% for the player name
# - %display% for the player display name
# - %localtime% for the players local time
# - %ticks% for the in game ticks
# - %time% for the in game time (in regular format)
# - %players% for the online player count.
# - %max% for the max players.
# - %balance% for the balance of the player.
motd:
  enabled: true
  message:
  - '&8&m---------------------'
  - '&4Welcome back, &c%display%'
  - '&4Currently &c[&7%players%&4/&7%max%&c] &4online people'
  - '&c%localtime% &4is the current time'
  - '&4You have &c$%balance% &4in your balance'
  - '&4Type &c/rules &4for the rulebook of the server!'
  - '&8&m---------------------'

# JOINING & NEW PLAYERS #
# Where we can choose the join and leave messages, or disable them.
# Tags include: %player% and %time%
# If you set enabled to false it will remove the join message completely.
# For newbies, refer to http://minecraft-ids.grahamedgecombe.com for ID's.
# If no items given to the newbies, change kit: enabled to false
join:
  enabled: true
  message: '&e%player% joined the game.'
leave:
  enabled: true
  message: '&e%player% left the game.'
newbies:
  kit:
    enabled: true
    items:
    - 260
    - 272
    - 273
    - 274
    - 275
  broadcastWelcome: true
  message: '&dWelcome %player%, to the server! We hope you enjoy your stay!'
  
# SPAWN #
# What should the default spawn be?
default-spawn: default

# What spawn should we teleport new players to?
newbies-spawn: new
  
# GOD #
# Notifies whether the player should be told if they have god mode when they join.
god:
  notify: true
  message: '&6God: &eGod mode is currently enabled'
  
# TPA #
# Has the timeout in seconds for the tp request, and whether the timeout for the request is enabled or not
tpa:
  timeout: true
  seconds: 60
  
# MSG #
# Changes the formats of msg
msg:
  format-sender: '&6Message &e« &6%target%&8 &c<- &f%message%'
  format-target: '&6Message &e» &6%sender%&8 &c-> &f%message%'
  
# BLOCK BREAK LISTENING #
# Adds blocks to a blacklist that nobody can remove, and other things.
# For block ID's visit http://minecraft-ids.grahamedgecombe.com
# and if it does, cancel the block break, unless the player has the permission bottomline.break.animalfence
# Set to false if you want it to work.
block:
  blocks:
  - 7
  - 49

# AFK #
# Changes the message broadcasted to everyone and whether we should broadcast it or not
afk:
  broadcast: true
  afk: '&7%player% has gone AFK!'
  no-afk: '&7%player% is no longer AFK!'

# WEATHER & WORLDS #
# Should we stop the weather changing on the server?
# Add world names to the worlds string list to choose worlds
weatherchange:
  change: true
  worlds:
  - world
  
# Should we either let people smite ops or not?
# And, should we warn the player when they've been striked?
strike:
  strike-ops: true
  warn-player: true

# Here, you have the option of disabling the death messages.
allow-death-messages: true

# INVENTORY #
# Whether to charge the players for clearing their inventory or not.
inventory:
  clear:
    pay: false
    amount: 100

# CHAT FORMATTING #
# Set the maximum and minimum amount of letters for nicknames
# The grammar option is whether we put a fullstop and a capital letter of every message
# without the exception of the permissions bottomline.chat.grammar
# Set the chat formatting with the colour codes and tags:
# - %player% <- does not include nicknames or prefixes
# - %displayname% <- this includes the prefix and suffix already.
# - %nickname% <- the nickname only
# - %message% <- the spoken message by the player
# ops-colour is to change the colour of default ops to show them out from
# everyone else in the chat.
nick:
  min: 3
  max: 16
chat:
  format: '&6%displayname%&7: &f%message%'
  grammar: true
ops-colour: '&c'

# GROUP FORMATTING #
# Group formatting is changing the format of the groups instead of the whole chat.
# This can change the colour of the message, prefixes etc.
# Please set the group names to lower case. It will ONLY look for lowercase names.
# This requires vault to work.
format-groups:
  enabled: false
  #default: '&7%player% &8> &f%message%'

# COMMAND SPY #
# Set the format of command spy and blacklist commands
cmdspy:
  format: '&8[&6Command Spy&8] &e%player% &7ran the command &e%command%'
  blacklist:
  - break
  - help
  - broadcast
  
# LIST #
# Should we make the list sorted by groups or list all players together?
# The sorting by groups requires Vault to get the groups.
list-sort: true

# SIGNS #
# Enable and disable signs here
# If there is a command that uses the same sign name, permissions will be enabled.
signs:
  feed: true
  heal: true
  
# SPAM FILTER #
# Should we enable the spam filter?
spam: true

# KITS #
# The kits section can be set out exactly like /i
# An example of spawning 10 cobblestone with the name of My favourite cobble! in red, and a lore of BottomLine with a 10 dollar fee would be like this:
# kits:
#   examplekit:
#     cost: 10
#     items:
#     - 4 10 name:&4My_favourite_cobble;lore:&aBottomLine
noKitPermission: '&cInsufficient permissions to use that kit!'
kits:
  example:
    cost: 0
    items:
    - 4 10 name:&4Introducing_kits;lore:&cTo_BottomLine!
  
# END OF CONFIGURATION FILE #
